# settings up our three databases with postgres
development:
  adapter: postgresql
  encoding: unicode
  database: nano_twitter_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: nano_twitter_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: nano_twitter_prod
  pool: 2
  username: your_username
  password: your_password
